# Generated by Django 5.1.6 on 2025-02-28 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cotisation',
            fields=[
                ('cot_id', models.AutoField(primary_key=True, serialize=False)),
                ('cot_type', models.CharField(max_length=45)),
                ('cot_amount', models.FloatField()),
            ],
            options={
                'db_table': 'ifa_cotisation',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('eve_id', models.AutoField(primary_key=True, serialize=False)),
                ('eve_title', models.CharField(max_length=45)),
                ('eve_description', models.TextField()),
                ('eve_date', models.DateField()),
                ('eve_location', models.CharField(max_length=255)),
                ('eve_price', models.FloatField()),
            ],
            options={
                'db_table': 'ifa_event',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('pro_id', models.AutoField(primary_key=True, serialize=False)),
                ('pro_title', models.CharField(max_length=45)),
                ('pro_description', models.TextField()),
                ('pro_budget', models.FloatField()),
            ],
            options={
                'db_table': 'ifa_project',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('usr_id', models.AutoField(primary_key=True, serialize=False)),
                ('usr_name', models.CharField(max_length=45)),
                ('usr_surname', models.CharField(max_length=45)),
                ('usr_birthdate', models.DateField()),
                ('usr_email', models.CharField(max_length=45)),
                ('usr_phone_number', models.CharField(max_length=45)),
                ('usr_status', models.BooleanField()),
                ('usr_cgu', models.BooleanField()),
                ('usr_type', models.CharField(max_length=45)),
                ('usr_stripe_id', models.BigIntegerField()),
            ],
            options={
                'db_table': 'ifa_user',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('img_id', models.AutoField(primary_key=True, serialize=False)),
                ('img_url', models.CharField(max_length=255)),
                ('img_position', models.IntegerField(verbose_name=10)),
                ('img_event_id', models.ForeignKey(db_column='eve_id', on_delete=django.db.models.deletion.CASCADE, to='django_rest.event')),
            ],
            options={
                'db_table': 'ifa_image',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('pay_id', models.AutoField(primary_key=True, serialize=False)),
                ('pay_creation_time', models.DateTimeField(auto_now_add=True)),
                ('pay_amount', models.FloatField()),
                ('pay_stripe_id', models.BigIntegerField()),
                ('pay_status', models.CharField(max_length=45)),
                ('pay_currency', models.CharField(max_length=45)),
                ('pay_cot_id', models.ForeignKey(db_column='cot_id', on_delete=django.db.models.deletion.CASCADE, to='django_rest.cotisation')),
                ('pay_event_id', models.ForeignKey(db_column='eve_id', on_delete=django.db.models.deletion.CASCADE, to='django_rest.event')),
            ],
            options={
                'db_table': 'ifa_payment',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('doc_id', models.AutoField(primary_key=True, serialize=False)),
                ('doc_url', models.CharField(max_length=255)),
                ('pro_user_id', models.ForeignKey(db_column='pro_id', on_delete=django.db.models.deletion.CASCADE, to='django_rest.project')),
            ],
            options={
                'db_table': 'ifa_document',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='pro_user_id',
            field=models.ForeignKey(db_column='usr_id', on_delete=django.db.models.deletion.CASCADE, to='django_rest.user'),
        ),
        migrations.AddField(
            model_name='event',
            name='eve_user_id',
            field=models.ForeignKey(db_column='usr_id', on_delete=django.db.models.deletion.CASCADE, to='django_rest.user'),
        ),
        migrations.AddField(
            model_name='cotisation',
            name='cot_user_id',
            field=models.ForeignKey(db_column='usr_id', on_delete=django.db.models.deletion.CASCADE, to='django_rest.user'),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('art_id', models.AutoField(primary_key=True, serialize=False)),
                ('art_title', models.CharField(max_length=255)),
                ('art_text', models.TextField()),
                ('art_creation_time', models.DateTimeField(auto_now_add=True)),
                ('art_user_id', models.ForeignKey(db_column='usr_id', on_delete=django.db.models.deletion.CASCADE, to='django_rest.user')),
            ],
            options={
                'db_table': 'ifa_article',
            },
        ),
    ]
